version: "3"

services:
  php:
    container_name: "php8-fpm"
    build: .
    volumes:
      - .:/var/www/html
    networks:
      - php-network

  web:
    container_name: "nginx"
    image: nginx:1.19
    volumes:
      - .:/usr/share/nginx/html
      - ./templates:/etc/nginx/templates
    ports:
      - "8080:80"
    command: [nginx-debug, '-g', 'daemon off;']
    links:
      - "php"
    environment:
      - NGINX_HOST=foobar.test
      - NGINX_PORT=8080
    networks:
      - php-network

networks:
  php-network:
    driver: bridge